"""Infrastructure layer: the concrete adapters of the assistant.

Three families live here: the SQLite persistence adapters (which are also the only
code that imports :mod:`sqlite3`), the Cline file-channel worker adapter and the
consultative advisor adapters (OpenAI, Claude, Grok). Nothing in ``domain``,
``ports`` or ``application`` imports this package except the composition root and
tests.

The private ``_http`` module holds the provider-neutral machinery the advisor
adapters share (HTTP DTOs, ``urllib`` transport, transport error, retry
classification, redaction, primitive validators, finding-id helper, price
model). It is **not** part of the public surface: the names below that originate
there are re-exported only because they were already public.
"""

from __future__ import annotations

from .claude import (
    CLAUDE_API_KEY_ENV_VAR,
    CLAUDE_API_VERSION,
    CLAUDE_MESSAGES_URL,
    CLAUDE_MODEL_ENV_VAR,
    CLAUDE_PROVIDER,
    CRITICAL_REVIEWER_ROLE,
    DEFAULT_CLAUDE_MAX_OUTPUT_TOKENS,
    DEFAULT_CLAUDE_MODEL,
    ClaudeAdvisorAbstainError,
    ClaudeAdvisorAdapter,
    ClaudeAdvisorError,
    ClaudeAdvisorHttpError,
    ClaudeAdvisorInvalidResponseError,
    ClaudeAdvisorRateLimitError,
    ClaudeAdvisorTimeoutError,
    ClaudeAdvisorTransportError,
    ClaudeMissingApiKeyError,
    resolve_claude_model,
)
from .cline import (
    DEFAULT_EXCHANGE_DIR,
    DEFAULT_PROTOCOL,
    DIRECTIVE_KIND,
    DIRECTIVE_VERSION,
    ClineWorkerAdapter,
    ClineWorkerError,
    ReportMismatchError,
    ReportNotAvailableError,
    ReportParseError,
    TaskDispatchError,
)
from .cost import SqliteCostPlugin
from .deepseek import (
    DEEPSEEK_API_KEY_ENV_VAR,
    DEEPSEEK_CHAT_COMPLETIONS_URL,
    DEEPSEEK_MODEL_ENV_VAR,
    DEEPSEEK_PROVIDER,
    DEFAULT_DEEPSEEK_MAX_OUTPUT_TOKENS,
    DEFAULT_DEEPSEEK_MODEL,
    INDEPENDENT_REVIEWER_ROLE,
    DeepSeekAdvisorAbstainError,
    DeepSeekAdvisorAdapter,
    DeepSeekAdvisorError,
    DeepSeekAdvisorHttpError,
    DeepSeekAdvisorInvalidResponseError,
    DeepSeekAdvisorRateLimitError,
    DeepSeekAdvisorTimeoutError,
    DeepSeekAdvisorTransportError,
    DeepSeekMissingApiKeyError,
    resolve_deepseek_model,
)
from .disabled import (
    DISABLED_PROVIDER,
    DISABLED_REASON,
    DISABLED_ROLE,
    DisabledAdvisorAbstainError,
    DisabledAdvisorAdapter,
    DisabledAdvisorError,
)
from .excel_reporting import SHEET_NAMES, ExcelReportingAdapter
from .deliberation_lead import (
    DEFAULT_DELIBERATION_MAX_OUTPUT_TOKENS,
    DEFAULT_DELIBERATION_TEMPERATURE,
    DELIBERATION_AGENT_ROLE,
    DELIBERATION_LEAD_PROVIDERS,
    DELIBERATION_LEAD_ROLE,
    DeliberationAdapterError,
    DeliberationAgentAdapter,
    DeliberationHttpError,
    DeliberationInvalidResponseError,
    DeliberationLeadAdapter,
    DeliberationMissingApiKeyError,
    DeliberationRateLimitError,
    DeliberationTransportError,
    profile_for,
    resolve_deliberation_model,
)
from .grok import (
    CHALLENGER_ROLE,
    DEFAULT_GROK_MAX_OUTPUT_TOKENS,
    DEFAULT_GROK_MODEL,
    GROK_CHAT_COMPLETIONS_URL,
    GROK_MODEL_ENV_VAR,
    GROK_PROVIDER,
    XAI_API_KEY_ENV_VAR,
    GrokAdvisorAbstainError,
    GrokAdvisorAdapter,
    GrokAdvisorError,
    GrokAdvisorHttpError,
    GrokAdvisorInvalidResponseError,
    GrokAdvisorRateLimitError,
    GrokAdvisorTimeoutError,
    GrokAdvisorTransportError,
    GrokMissingApiKeyError,
    resolve_grok_model,
)
from .markdown_reporting import SECTION_NAMES, MarkdownReportingAdapter
from .migrations import (
    AUDIT_TABLE_NAME,
    BOOTSTRAP_SCHEMA_SQL,
    CHANGE_REQUEST_TABLE_NAME,
    COST_TABLE_NAME,
    DELIBERATION_ARTIFACT_TABLE_NAME,
    DELIBERATION_RUN_TABLE_NAME,
    MIGRATIONS,
    PROPOSAL_TABLE_NAME,
    SUPERVISION_TABLE_NAME,
    TABLE_NAMES,
    Migration,
)
# The provider-neutral transport/price/validator names below are re-exported
# through ``.openai`` (their Step 12 public path) although they now live in the
# private ``._http`` module. Re-exporting them here keeps this package's public
# surface - and therefore ``__all__`` - exactly what it was before the extraction.
from .openai import (
    ABSTAIN_REASON_FALLBACK,
    DEFAULT_BACKOFF_SCHEDULE,
    DEFAULT_MAX_OUTPUT_TOKENS,
    DEFAULT_MAX_RETRIES,
    DEFAULT_OPENAI_MODEL,
    DEFAULT_TIMEOUT_SECONDS,
    IMPLEMENTATION_ANALYST_ROLE,
    OPENAI_API_KEY_ENV_VAR,
    OPENAI_CHAT_COMPLETIONS_URL,
    OPENAI_PROVIDER,
    UNKNOWN_PRICE,
    HttpRequest,
    HttpResponse,
    HttpTransportError,
    MissingApiKeyError,
    ModelPrice,
    OpenAIAdvisorAbstainError,
    OpenAIAdvisorAdapter,
    OpenAIAdvisorError,
    OpenAIAdvisorHttpError,
    OpenAIAdvisorInvalidResponseError,
    OpenAIAdvisorRateLimitError,
    OpenAIAdvisorTimeoutError,
    OpenAIAdvisorTransportError,
    urllib_transport,
)
from .openai_judge import (
    DEFAULT_JUDGE_MAX_OUTPUT_TOKENS,
    DEFAULT_OPENAI_JUDGE_MODEL,
    EVIDENCE_JUDGE_ROLE,
    OPENAI_JUDGE_FALLBACK_TARGET,
    OPENAI_JUDGE_MODEL_ENV_VAR,
    OpenAIJudgeAdapter,
    resolve_openai_judge_model,
)
from .repositories import (
    SqliteADRRepository,
    SqliteArchitectureChangeRequestRepository,
    SqliteArchitectureProposalRepository,
    SqliteArchitectureVersionRepository,
    SqliteAuditRepository,
    SqliteDecisionRepository,
    SqliteFindingRepository,
    SqliteProjectRepository,
    SqliteRiskRepository,
    SqliteStepRepository,
    SqliteSupervisionRepository,
    SqliteTaskRepository,
)
from .scripted_supervisor import (
    DEFAULT_SCRIPTED_PROVIDER,
    ScriptedSupervisor,
    no_action,
    scripted_result,
)
from .storage import SqliteStorage
from .sqlite import (
    DEFAULT_DATABASE_PATH,
    DatabasePath,
    SqliteTransactionPort,
    applied_versions,
    apply_migrations,
    close_database,
    open_database,
)

__all__ = [
    # connection + migrations
    "DEFAULT_DATABASE_PATH",
    "DatabasePath",
    "open_database",
    "close_database",
    "apply_migrations",
    "applied_versions",
    "SqliteTransactionPort",
    "Migration",
    "MIGRATIONS",
    "BOOTSTRAP_SCHEMA_SQL",
    "TABLE_NAMES",
    "AUDIT_TABLE_NAME",
    "CHANGE_REQUEST_TABLE_NAME",
    "COST_TABLE_NAME",
    "PROPOSAL_TABLE_NAME",
    "SUPERVISION_TABLE_NAME",
    "DELIBERATION_RUN_TABLE_NAME",
    "DELIBERATION_ARTIFACT_TABLE_NAME",
    # adapters
    "SqliteStorage",
    "SqliteCostPlugin",
    # Excel reporting adapter (Step 18)
    "ExcelReportingAdapter",
    "SHEET_NAMES",
    # Markdown reporting adapter (Step 21)
    "MarkdownReportingAdapter",
    "SECTION_NAMES",
    "SqliteProjectRepository",
    "SqliteStepRepository",
    "SqliteTaskRepository",
    "SqliteArchitectureVersionRepository",
    "SqliteArchitectureChangeRequestRepository",
    "SqliteArchitectureProposalRepository",
    "SqliteSupervisionRepository",
    "SqliteADRRepository",
    "SqliteRiskRepository",
    "SqliteFindingRepository",
    "SqliteDecisionRepository",
    "SqliteAuditRepository",
    # Cline file-channel worker adapter
    "ClineWorkerAdapter",
    "DEFAULT_EXCHANGE_DIR",
    "DEFAULT_PROTOCOL",
    "DIRECTIVE_KIND",
    "DIRECTIVE_VERSION",
    "ClineWorkerError",
    "TaskDispatchError",
    "ReportNotAvailableError",
    "ReportParseError",
    "ReportMismatchError",
    # offline scripted supervisor (Step 28 Phase 1)
    "ScriptedSupervisor",
    "DEFAULT_SCRIPTED_PROVIDER",
    "scripted_result",
    "no_action",
    # OpenAI advisor adapter (Step 12)
    "OpenAIAdvisorAdapter",
    "OpenAIAdvisorError",
    "MissingApiKeyError",
    "OpenAIAdvisorTransportError",
    "OpenAIAdvisorTimeoutError",
    "OpenAIAdvisorRateLimitError",
    "OpenAIAdvisorHttpError",
    "OpenAIAdvisorInvalidResponseError",
    "OpenAIAdvisorAbstainError",
    "HttpTransportError",
    "HttpRequest",
    "HttpResponse",
    "urllib_transport",
    "ModelPrice",
    "UNKNOWN_PRICE",
    "OPENAI_PROVIDER",
    "IMPLEMENTATION_ANALYST_ROLE",
    "DEFAULT_OPENAI_MODEL",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_BACKOFF_SCHEDULE",
    "DEFAULT_MAX_OUTPUT_TOKENS",
    "ABSTAIN_REASON_FALLBACK",
    "OPENAI_CHAT_COMPLETIONS_URL",
    "OPENAI_API_KEY_ENV_VAR",
    # Claude advisor adapter (Step 13)
    "ClaudeAdvisorAdapter",
    "ClaudeAdvisorError",
    "ClaudeMissingApiKeyError",
    "ClaudeAdvisorTransportError",
    "ClaudeAdvisorTimeoutError",
    "ClaudeAdvisorRateLimitError",
    "ClaudeAdvisorHttpError",
    "ClaudeAdvisorInvalidResponseError",
    "ClaudeAdvisorAbstainError",
    "CLAUDE_PROVIDER",
    "CRITICAL_REVIEWER_ROLE",
    "DEFAULT_CLAUDE_MODEL",
    "CLAUDE_MODEL_ENV_VAR",
    "CLAUDE_MESSAGES_URL",
    "CLAUDE_API_KEY_ENV_VAR",
    "CLAUDE_API_VERSION",
    "DEFAULT_CLAUDE_MAX_OUTPUT_TOKENS",
    "resolve_claude_model",
    # Grok advisor adapter (Step 14)
    "GrokAdvisorAdapter",
    "GrokAdvisorError",
    "GrokMissingApiKeyError",
    "GrokAdvisorTransportError",
    "GrokAdvisorTimeoutError",
    "GrokAdvisorRateLimitError",
    "GrokAdvisorHttpError",
    "GrokAdvisorInvalidResponseError",
    "GrokAdvisorAbstainError",
    "GROK_PROVIDER",
    "CHALLENGER_ROLE",
    "DEFAULT_GROK_MODEL",
    "GROK_MODEL_ENV_VAR",
    "GROK_CHAT_COMPLETIONS_URL",
    "XAI_API_KEY_ENV_VAR",
    "DEFAULT_GROK_MAX_OUTPUT_TOKENS",
    "resolve_grok_model",
    # DeepSeek advisor adapter (independent AdvisorPort implementation)
    "DeepSeekAdvisorAdapter",
    "DeepSeekAdvisorError",
    "DeepSeekMissingApiKeyError",
    "DeepSeekAdvisorTransportError",
    "DeepSeekAdvisorTimeoutError",
    "DeepSeekAdvisorRateLimitError",
    "DeepSeekAdvisorHttpError",
    "DeepSeekAdvisorInvalidResponseError",
    "DeepSeekAdvisorAbstainError",
    "DEEPSEEK_PROVIDER",
    "INDEPENDENT_REVIEWER_ROLE",
    "DEFAULT_DEEPSEEK_MODEL",
    "DEEPSEEK_MODEL_ENV_VAR",
    "DEEPSEEK_CHAT_COMPLETIONS_URL",
    "DEEPSEEK_API_KEY_ENV_VAR",
    "DEFAULT_DEEPSEEK_MAX_OUTPUT_TOKENS",
    "resolve_deepseek_model",
    # the disabled advisor (an explicit "no provider" AdvisorPort)
    "DisabledAdvisorAdapter",
    "DisabledAdvisorError",
    "DisabledAdvisorAbstainError",
    "DISABLED_PROVIDER",
    "DISABLED_ROLE",
    "DISABLED_REASON",
    # OpenAI judge adapter (Step 16)
    "OpenAIJudgeAdapter",
    "EVIDENCE_JUDGE_ROLE",
    "DEFAULT_OPENAI_JUDGE_MODEL",
    "OPENAI_JUDGE_MODEL_ENV_VAR",
    "OPENAI_JUDGE_FALLBACK_TARGET",
    "DEFAULT_JUDGE_MAX_OUTPUT_TOKENS",
    "resolve_openai_judge_model",
    # the deliberation adapters (Step 29: one architect seat + one chair)
    "DeliberationAgentAdapter",
    "DeliberationLeadAdapter",
    "DeliberationAdapterError",
    "DeliberationMissingApiKeyError",
    "DeliberationTransportError",
    "DeliberationHttpError",
    "DeliberationRateLimitError",
    "DeliberationInvalidResponseError",
    "DELIBERATION_AGENT_ROLE",
    "DELIBERATION_LEAD_ROLE",
    "DELIBERATION_LEAD_PROVIDERS",
    "DEFAULT_DELIBERATION_MAX_OUTPUT_TOKENS",
    "DEFAULT_DELIBERATION_TEMPERATURE",
    "profile_for",
    "resolve_deliberation_model",
]
