"""Application layer: use-cases orchestrating the domain through ports.

The application layer depends on ``domain`` and ``ports`` only. It never imports
``infrastructure`` or ``sqlite3``.
"""

from __future__ import annotations

from .adr_manager import (
    ADR_TRANSITIONS,
    ADRManager,
    AdrManagerError,
    AdrNotFoundError,
    InvalidAdrStatusTransitionError,
    InvalidSupersessionError,
)
from .architecture_bootstrap import (
    BOOTSTRAP_ADRS,
    BOOTSTRAP_RISKS,
    PROJECT_NAME,
    PROJECT_PLAN_VERSION,
    RETROSPECTIVE_NOTE,
    AdrSpec,
    ArchitectureBootstrap,
    BootstrapConflictError,
    BootstrapError,
    BootstrapOutcome,
    BootstrapSummary,
    RiskSpec,
    make_project,
)
from .context import (
    SCHEMA_VERSION,
    ContextBuilder,
    ContextError,
    ContextInvariantError,
    ContextSnapshot,
    ProjectNotFoundError,
    StepNotFoundError,
)
from .architecture_versioning import (
    COMPOSITION_ROOT_ADR,
    STEP_9_PROVENANCE,
    ArchitectureVersioning,
    ArchitectureVersioningConflictError,
    ArchitectureVersioningError,
    VersioningSummary,
)
from .architecture_evolution import (
    ArchitectureEvolution,
    ArchitectureEvolutionConflictError,
    ArchitectureEvolutionError,
    ArchitectureEvolutionNotApprovedError,
    ArchitectureEvolutionNotFoundError,
    EvolutionSummary,
    LinkedChange,
)
from .loop_policy import (
    ReviewOutcome,
    decide_review,
    requires_approval,
)
from .orchestrator import (
    DEFAULT_REPORT_SCHEMA,
    DEFAULT_STEP_TIMEOUT,
    DEFAULT_TASK_INSTRUCTIONS,
    HALTING_REASONS,
    LoopInvariantError,
    LoopStatus,
    Orchestrator,
    OrchestratorError,
    TickResult,
)
from .scheduler import (
    DEFAULT_MAX_ITERATIONS,
    LoopHealth,
    Scheduler,
    SchedulerRun,
)
from .realization_control import (
    RealizationControlError,
    RealizationControlUseCase,
)
from .risk_manager import (
    RISK_TRANSITIONS,
    InvalidRiskStatusTransitionError,
    RiskManager,
    RiskManagerError,
    RiskNotFoundError,
)
from .plugin_core import (
    PluginAlreadyRegisteredError,
    PluginBinding,
    PluginDefaultNotSetError,
    PluginError,
    PluginNotFoundError,
    PluginRegistry,
)
from .evidence_merger import (
    AdvisorObservation,
    EvidenceConflict,
    EvidenceIdentityCollisionError,
    EvidenceMergerError,
    EvidenceRelation,
    EvidenceView,
    ObservationOutcome,
    ObservationStatus,
    merge_evidence,
)
from .decision_engine import (
    DecisionEngineError,
    DecisionResult,
    decide_from_observations,
    synthesize_decision,
)
from .judge import (
    JudgeError,
    JudgeJudgment,
    JudgeRun,
    JudgeUseCase,
    build_judge_conflict,
)
from .reporting import (
    REPORT_SCHEMA_VERSION,
    ProjectMissingError,
    ReportBuilder,
    ReportingError,
    ReportingInvariantError,
    ReportSnapshot,
)
from .monitor import Monitor
from .eventlog import (
    EVENT_FIELDS,
    EVENT_LEVEL_ERROR,
    EVENT_LEVEL_INFO,
    EVENT_LEVEL_WARN,
    EVENT_LEVELS,
    LOG_ACTION_LIMIT,
    LOG_COMPONENTS,
    LOG_MESSAGE_LIMIT,
    LOG_REVIEW_ID_LIMIT,
    REDACTION_MARK,
    LogEventError,
    build_event,
    component_for,
    exception_reason,
    sanitize_text,
)
from .architecture_review import (
    DEFAULT_REVIEW_QUESTION,
    JUDGE_STATUS_ERROR,
    JUDGE_STATUS_NOT_CONSULTED,
    JUDGE_STATUS_OK,
    JUDGE_STATUS_UNAVAILABLE,
    AdvisorReviewer,
    ArchitectureReview,
    ArchitectureReviewResult,
    JudgeOutcome,
    ReviewError,
    ReviewStage,
)
from .plan_loader import (
    MAX_ISSUES,
    MAX_PLAN_CHARS,
    MAX_PLAN_STEPS,
    PLAN_SCHEMA_VERSION,
    Plan,
    PlanActorRequiredError,
    PlanConflictError,
    PlanError,
    PlanFormatError,
    PlanImportResult,
    PlanInvariantError,
    PlanIssue,
    PlanLoader,
    PlanPreview,
    PlanProjectMismatchError,
    PlanReasonRequiredError,
    PlanStepSpec,
    PlanVersionMismatchError,
    parse_plan,
)
from .architecture_synthesis import (
    DETERMINISTIC_SOURCE,
    MAX_DIGEST_ITEMS,
    MAX_PROPOSAL_ITEMS,
    MAX_PROPOSAL_TEXT,
    PROPOSAL_CONTENT_FIELDS,
    PROPOSAL_SCHEMA_VERSION,
    ArchitectureSynthesis,
    SynthesisActorRequiredError,
    SynthesisError,
    SynthesisInsufficientEvidenceError,
    SynthesisNotFoundError,
    SynthesisProviderError,
    SynthesisReasonRequiredError,
    SynthesisResponseError,
    fingerprint_matches,
    proposal_fingerprint,
)
from .proposal_approval import (
    ProposalActorRequiredError,
    ProposalApproval,
    ProposalApprovalError,
    ProposalDecisionConflictError,
    ProposalFeedbackRequiredError,
    ProposalNotApprovableError,
    ProposalNotFoundError,
    ProposalReasonRequiredError,
)
from .supervision import (
    DEFAULT_MALFORMED_STABILITY,
    DEFAULT_MALFORMED_TIMEOUT,
    DIRECTIVE_SCHEMA_VERSION,
    LIVE_STEP_STATES,
    MAX_REPORT_BYTES,
    MAX_SUPERVISOR_SECTION,
    SUPERVISION_DISABLED_REASON,
    SUPERVISION_DISABLED_STATUS,
    SUPERVISION_DISABLED_VERDICT_REASON,
    SUPERVISOR_COMPONENT,
    Supervision,
    SupervisionActorRequiredError,
    SupervisionAnalysis,
    SupervisionDisabledError,
    SupervisionError,
    SupervisionGate,
    SupervisionNotFoundError,
    SupervisionNotSendableError,
    SupervisionReasonRequiredError,
    SupervisionStaleError,
    WaitingFor,
    report_hash,
    supervision_identity,
)
from .supervisor_policy import (
    AUTO_SEND_ACTIONS,
    MAX_INSTRUCTION_LENGTH,
    UNSAFE_INSTRUCTION_TERMS,
    SendDecision,
    SendVerdict,
    decide_send,
    unsafe_terms,
)
from .supervisor_runtime import (
    DEFAULT_POLL_INTERVAL_SECONDS,
    MAX_TICK_RESULTS,
    RuntimeState,
    RuntimeTick,
    SupervisorRuntime,
)
from .human_override import (
    HumanOverride,
    HumanOverrideError,
    OverrideActorRequiredError,
    OverrideInvariantError,
    OverrideNoChangeError,
    OverrideProjectNotFoundError,
    OverrideReasonRequiredError,
    OverrideStepNotFoundError,
    OverrideTransitionError,
)
from .approval import (
    ApprovalActorRequiredError,
    ApprovalError,
    ApprovalGate,
    ApprovalReasonRequiredError,
    ApprovalStepNotFoundError,
    ApprovalTransitionError,
)

__all__ = [
    # context
    "SCHEMA_VERSION",
    "ContextBuilder",
    "ContextError",
    "ContextInvariantError",
    "ContextSnapshot",
    "ProjectNotFoundError",
    "StepNotFoundError",
    # ADR
    "ADRManager",
    "ADR_TRANSITIONS",
    "AdrManagerError",
    "AdrNotFoundError",
    "InvalidAdrStatusTransitionError",
    "InvalidSupersessionError",
    # risk
    "RiskManager",
    "RISK_TRANSITIONS",
    "RiskManagerError",
    "RiskNotFoundError",
    "InvalidRiskStatusTransitionError",
    # plugin core
    "PluginRegistry",
    "PluginBinding",
    "PluginError",
    "PluginNotFoundError",
    "PluginAlreadyRegisteredError",
    "PluginDefaultNotSetError",
    # architecture bootstrap
    "ArchitectureBootstrap",
    "BootstrapOutcome",
    "BootstrapSummary",
    "BootstrapError",
    "BootstrapConflictError",
    "AdrSpec",
    "RiskSpec",
    "BOOTSTRAP_ADRS",
    "BOOTSTRAP_RISKS",
    "RETROSPECTIVE_NOTE",
    "PROJECT_NAME",
    "PROJECT_PLAN_VERSION",
    "make_project",
    # architecture versioning (minimal versioned baseline update)
    "ArchitectureVersioning",
    "ArchitectureVersioningError",
    "ArchitectureVersioningConflictError",
    "VersioningSummary",
    "COMPOSITION_ROOT_ADR",
    "STEP_9_PROVENANCE",
    # loop policies
    "requires_approval",
    "ReviewOutcome",
    "decide_review",
    # orchestrator
    "Orchestrator",
    "OrchestratorError",
    "LoopInvariantError",
    "LoopStatus",
    "TickResult",
    "DEFAULT_STEP_TIMEOUT",
    "DEFAULT_TASK_INSTRUCTIONS",
    "DEFAULT_REPORT_SCHEMA",
    "HALTING_REASONS",
    # scheduler
    "Scheduler",
    "SchedulerRun",
    "LoopHealth",
    "DEFAULT_MAX_ITERATIONS",
    # realization control (fail-closed architecture gate)
    "RealizationControlUseCase",
    "RealizationControlError",
    # architecture evolution (persistent change requests)
    "ArchitectureEvolution",
    "ArchitectureEvolutionError",
    "ArchitectureEvolutionNotFoundError",
    "ArchitectureEvolutionConflictError",
    "ArchitectureEvolutionNotApprovedError",
    "EvolutionSummary",
    "LinkedChange",
    # evidence merger + decision engine (Step 15)
    "AdvisorObservation",
    "ObservationStatus",
    "EvidenceRelation",
    "ObservationOutcome",
    "EvidenceConflict",
    "EvidenceView",
    "EvidenceMergerError",
    "EvidenceIdentityCollisionError",
    "merge_evidence",
    "DecisionResult",
    "DecisionEngineError",
    "synthesize_decision",
    "decide_from_observations",
    # judge use-case (Step 16)
    "JudgeUseCase",
    "JudgeRun",
    "JudgeJudgment",
    "JudgeError",
    "build_judge_conflict",
    # reporting projection (Step 18)
    "ReportBuilder",
    "ReportSnapshot",
    "REPORT_SCHEMA_VERSION",
    "ReportingError",
    "ProjectMissingError",
    "ReportingInvariantError",
    # project monitor (Step 19)
    "Monitor",
    # human override (Step 20, controlled write)
    "HumanOverride",
    "HumanOverrideError",
    "OverrideActorRequiredError",
    "OverrideReasonRequiredError",
    "OverrideProjectNotFoundError",
    "OverrideStepNotFoundError",
    "OverrideInvariantError",
    "OverrideNoChangeError",
    "OverrideTransitionError",
    # human approval gate (Step 23, controlled write)
    "ApprovalGate",
    "ApprovalError",
    "ApprovalActorRequiredError",
    "ApprovalReasonRequiredError",
    "ApprovalStepNotFoundError",
    "ApprovalTransitionError",
    # plan loader (Step 25, controlled initial import)
    "PlanLoader",
    "PlanPreview",
    "PlanImportResult",
    "PlanIssue",
    "PlanStepSpec",
    "Plan",
    "parse_plan",
    "PLAN_SCHEMA_VERSION",
    "MAX_PLAN_STEPS",
    "MAX_PLAN_CHARS",
    "MAX_ISSUES",
    "PlanError",
    "PlanFormatError",
    "PlanConflictError",
    "PlanProjectMismatchError",
    "PlanVersionMismatchError",
    "PlanInvariantError",
    "PlanActorRequiredError",
    "PlanReasonRequiredError",
    # three-advisor architecture review (Step 26, advisory read-only)
    "ArchitectureReview",
    "ArchitectureReviewResult",
    "AdvisorReviewer",
    "ReviewStage",
    "JudgeOutcome",
    "ReviewError",
    "DEFAULT_REVIEW_QUESTION",
    "JUDGE_STATUS_OK",
    "JUDGE_STATUS_ERROR",
    "JUDGE_STATUS_NOT_CONSULTED",
    "JUDGE_STATUS_UNAVAILABLE",
    # the managed-project architecture proposal (Step 27, project-scoped)
    "ArchitectureSynthesis",
    "SynthesisError",
    "SynthesisInsufficientEvidenceError",
    "SynthesisActorRequiredError",
    "SynthesisReasonRequiredError",
    "SynthesisProviderError",
    "SynthesisResponseError",
    "SynthesisNotFoundError",
    "PROPOSAL_SCHEMA_VERSION",
    "PROPOSAL_CONTENT_FIELDS",
    "MAX_PROPOSAL_ITEMS",
    "MAX_PROPOSAL_TEXT",
    "MAX_DIGEST_ITEMS",
    "DETERMINISTIC_SOURCE",
    "proposal_fingerprint",
    "fingerprint_matches",
    # the proposal approval human write path (Step 27, project-scoped)
    "ProposalApproval",
    "ProposalApprovalError",
    "ProposalNotFoundError",
    "ProposalActorRequiredError",
    "ProposalReasonRequiredError",
    "ProposalFeedbackRequiredError",
    "ProposalNotApprovableError",
    "ProposalDecisionConflictError",
    # the log-event contract (Step 27, ephemeral operator-facing logs)
    "EVENT_FIELDS",
    # === Step 28 Phase 1: supervision (advisory analysis of one worker report)
    "SUPERVISION_DISABLED_STATUS",
    "SUPERVISION_DISABLED_REASON",
    "SUPERVISION_DISABLED_VERDICT_REASON",
    "SUPERVISOR_COMPONENT",
    "SupervisionGate",
    "Supervision",
    "SupervisionError",
    "SupervisionNotFoundError",
    "SupervisionActorRequiredError",
    "SupervisionReasonRequiredError",
    "SupervisionNotSendableError",
    "SupervisionDisabledError",
    "SupervisionStaleError",
    "SupervisionAnalysis",
    "WaitingFor",
    "report_hash",
    "supervision_identity",
    "MAX_REPORT_BYTES",
    "MAX_SUPERVISOR_SECTION",
    "DIRECTIVE_SCHEMA_VERSION",
    "DEFAULT_MALFORMED_STABILITY",
    "DEFAULT_MALFORMED_TIMEOUT",
    "LIVE_STEP_STATES",
    "SendDecision",
    "SendVerdict",
    "AUTO_SEND_ACTIONS",
    "UNSAFE_INSTRUCTION_TERMS",
    "MAX_INSTRUCTION_LENGTH",
    "decide_send",
    "unsafe_terms",
    "SupervisorRuntime",
    "RuntimeState",
    "RuntimeTick",
    "DEFAULT_POLL_INTERVAL_SECONDS",
    "MAX_TICK_RESULTS",
    "EVENT_LEVELS",
    "EVENT_LEVEL_INFO",
    "EVENT_LEVEL_WARN",
    "EVENT_LEVEL_ERROR",
    "LOG_COMPONENTS",
    "LOG_MESSAGE_LIMIT",
    "LOG_ACTION_LIMIT",
    "LOG_REVIEW_ID_LIMIT",
    "REDACTION_MARK",
    "LogEventError",
    "build_event",
    "component_for",
    "exception_reason",
    "sanitize_text",
]
