"""Domain layer: enums, frozen domain models and deterministic FSMs.

This package is dependency-free (standard library only) and contains no
persistence, network, UI or plugin code.
"""

from __future__ import annotations

from .audit import (
    AuditAction,
    AuditEntityType,
    AuditEntry,
)
from .enums import (
    ACRStatus,
    ADRStatus,
    DecisionStatus,
    Mode,
    Phase,
    ReportStatus,
    RiskLevel,
    RiskStatus,
    Severity,
    StepEvent,
    StepState,
    TaskEvent,
    TaskState,
)
from .fsm import (
    STEP_TERMINAL_STATES,
    STEP_TRANSITIONS,
    TASK_TERMINAL_STATES,
    TASK_TRANSITIONS,
    FiniteStateMachine,
    FSMError,
    InvalidTransitionError,
    StepStateMachine,
    TaskStateMachine,
)
from .models import (
    ADR,
    ArchitectureChangeRequest,
    ArchitectureVersion,
    Decision,
    DomainModel,
    Finding,
    Project,
    Risk,
    Step,
    Task,
    utc_now,
)
from .category import (
    CATEGORY_ID_MAX_LENGTH,
    CATEGORY_ID_PATTERN,
    LIBRARY_ENTRY_NAME,
    REGISTRY_HASH_ALGORITHM,
    REQUIRED_CATEGORY_ENTRIES,
    SPEC_ENTRY_NAME,
    SUPERVISOR_RULES_ENTRY_NAME,
    CatalogAuditAction,
    CatalogAuditEntry,
    Category,
    CategorySelection,
    CategoryState,
    CategoryView,
    compute_registry_hash,
    is_relative_category_path,
    is_valid_category_id,
)
from .category_spec import (
    SPEC_HASH_ALGORITHM,
    SPEC_HASH_PATTERN,
    SPEC_METADATA_FENCE_CLOSE,
    SPEC_METADATA_FENCE_OPEN,
    SPEC_METADATA_KEYS,
    SPEC_METADATA_ORDER,
    SPEC_SCHEMA_VERSION,
    CategorySpec,
    CategorySpecError,
    CategorySpecHashMismatchError,
    CategorySpecIdentityError,
    CategorySpecMalformedError,
    canonical_spec_bytes,
    canonical_spec_serialization,
    compute_spec_hash,
    normalize_spec_text,
    parse_category_spec,
)

__all__ = [
    # audit
    "AuditAction",
    "AuditEntityType",
    "AuditEntry",
    # enums
    "ACRStatus",
    "ADRStatus",
    "DecisionStatus",
    "Mode",
    "Phase",
    "ReportStatus",
    "RiskLevel",
    "RiskStatus",
    "Severity",
    "StepEvent",
    "StepState",
    "TaskEvent",
    "TaskState",
    # models
    "ADR",
    "ArchitectureChangeRequest",
    "ArchitectureVersion",
    "Decision",
    "DomainModel",
    "Finding",
    "Project",
    "Risk",
    "Step",
    "Task",
    "utc_now",
    # the global category catalog (Step 2)
    "Category",
    "CategoryState",
    "CategoryView",
    "CategorySelection",
    "CatalogAuditAction",
    "CatalogAuditEntry",
    "CATEGORY_ID_PATTERN",
    "CATEGORY_ID_MAX_LENGTH",
    "REQUIRED_CATEGORY_ENTRIES",
    "SPEC_ENTRY_NAME",
    "LIBRARY_ENTRY_NAME",
    "SUPERVISOR_RULES_ENTRY_NAME",
    "REGISTRY_HASH_ALGORITHM",
    "compute_registry_hash",
    "is_valid_category_id",
    "is_relative_category_path",
    # the mandatory per-category SPEC.md (Step 3)
    "CategorySpec",
    "CategorySpecError",
    "CategorySpecMalformedError",
    "CategorySpecHashMismatchError",
    "CategorySpecIdentityError",
    "SPEC_SCHEMA_VERSION",
    "SPEC_METADATA_ORDER",
    "SPEC_METADATA_KEYS",
    "SPEC_METADATA_FENCE_OPEN",
    "SPEC_METADATA_FENCE_CLOSE",
    "SPEC_HASH_ALGORITHM",
    "SPEC_HASH_PATTERN",
    "normalize_spec_text",
    "canonical_spec_serialization",
    "canonical_spec_bytes",
    "compute_spec_hash",
    "parse_category_spec",
    # fsm
    "FSMError",
    "FiniteStateMachine",
    "InvalidTransitionError",
    "StepStateMachine",
    "TaskStateMachine",
    "STEP_TRANSITIONS",
    "TASK_TRANSITIONS",
    "STEP_TERMINAL_STATES",
    "TASK_TERMINAL_STATES",
]
